[package]
name = "core-zk"
version.workspace = true
edition.workspace = true

[dependencies]
ark-groth16 = "0.5"
ark-bn254 = "0.5"
ark-std = "0.5"
ark-ff = "0.5.0"
ark-bls12-381 = "0.5.0"
ark-relations = "0.5"
ark-serialize = "0.5"
ark-snark = "0.5.1"
rand = "0.9.2"
